#include "opencl_source_map.hpp" 
namespace MNN { 
const char* groupnorm = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"__constant sampler_t SAMPLER=CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_NEAREST;\n"
"__kernel void groupnorm(__private int global_dim0,__private int global_dim1,__private int global_dim2,\n"
" __read_only image2d_t input,\n"
" __write_only image2d_t output,\n"
" __private const int width,\n"
" __private const int height,\n"
" __private const int channel,\n"
" __private const int groups,\n"
" __private const int group_channels,\n"
" __private const int batch,\n"
"#ifdef GAMMA_BETA\n"
" __global const FLOAT *gamma,\n"
" __global const FLOAT *beta,\n"
"#endif\n"
" __private float epsilon){\n"
" int3 pos=(int3)(get_global_id(0),get_global_id(1),get_global_id(2));\n"
" if (pos.x<global_dim0 && pos.y<global_dim1 && pos.z<global_dim2) {\n"
" const int b=pos.z;\n"
" const int ch=pos.x;\n"
" const int h=pos.y/height;\n"
" const int w=pos.y%height;\n"
" int group_id=ch/group_channels;\n"
" float sum=0.0f;\n"
" float sum_sq=0.0f;\n"
" int count=0;\n"
" for(int c=group_id*group_channels;c<(group_id+1)*group_channels;++c) {\n"
" int c4=c/4;\n"
" int c4_off=c%4;\n"
" int img_x=c4*width+w;\n"
" int img_y=b*height+h;\n"
" float4 vals=convert_float4(RI_F(input,SAMPLER,(int2)(img_x,img_y)));\n"
" float val;\n"
" if(c4_off==0) val=vals.x;\n"
" else if(c4_off==1) val=vals.y;\n"
" else if(c4_off==2) val=vals.z;\n"
" else val=vals.w;\n"
" sum+=val;\n"
" sum_sq+=val*val;\n"
" count++;\n"
" }\n"
" float mean=sum/(float)count;\n"
" float var=sum_sq/(float)count-mean*mean;\n"
" float inv_std=rsqrt(var+epsilon);\n"
" int c4=ch;\n"
" int img_x_out=c4*width+w;\n"
" int img_y_out=b*height+h;\n"
" float4 in_vals=convert_float4(RI_F(input,SAMPLER,(int2)(img_x_out,img_y_out)));\n"
" float4 out_vals;\n"
"#ifdef GAMMA_BETA\n"
" out_vals.x=(in_vals.x-mean)*inv_std*gamma[ch*4+0]+beta[ch*4+0];\n"
" out_vals.y=(in_vals.y-mean)*inv_std*gamma[ch*4+1]+beta[ch*4+1];\n"
" out_vals.z=(in_vals.z-mean)*inv_std*gamma[ch*4+2]+beta[ch*4+2];\n"
" out_vals.w=(in_vals.w-mean)*inv_std*gamma[ch*4+3]+beta[ch*4+3];\n"
"#else\n"
" out_vals.x=(in_vals.x-mean)*inv_std;\n"
" out_vals.y=(in_vals.y-mean)*inv_std;\n"
" out_vals.z=(in_vals.z-mean)*inv_std;\n"
" out_vals.w=(in_vals.w-mean)*inv_std;\n"
"#endif\n"
" WI_F(output,(int2)(img_x_out,img_y_out),CONVERT_FLOAT4(out_vals));\n"
" }\n"
"}\n"
;
} // namespace MNN
